Fail invalid function file or handler in the function image build phase. Clean up source files.

diff --git a/function-template/Dockerfile b/function-template/Dockerfile
--- a/function-template/Dockerfile
+++ b/function-template/Dockerfile
@@ -11,3 +11,12 @@ WORKDIR ${WORKDIR}
 COPY . .
 
 RUN mvn compile -Dmaven.test.skip=true -Dproject.build.sourceEncoding=UTF-8 -Dmaven.compiler.source=10 -Dmaven.compiler.target=10 dependency:build-classpath -Dmdep.outputFile=./cp.txt
+
+# Validate function file and given handler
+WORKDIR /validator
+
+RUN mvn install dependency:build-classpath -Dmdep.outputFile=./cp.txt && \
+    java -cp target/classes:${WORKDIR}/target/classes:$(<./cp.txt):$(<${WORKDIR}/cp.txt) io.dispatchframework.javabaseimage.Validator "${HANDLER}" || \
+    (echo "Invalid function file or handler" >&2 && exit 1)
+
+WORKDIR ${WORKDIR}
